env:
  commonjs: true
  es6: true
  node: true
  mocha: true
extends: ["eslint:recommended", "prettier"]
globals:
  Atomics: "readonly"
  SharedArrayBuffer: "readonly"
parserOptions:
  ecmaVersion: "latest"
  sourceType: "module"
rules:
  no-var: "error"
  semi: "error"
  indent: ["error", 2, { "SwitchCase": 1 }]
  linebreak-style: ["error", "unix"]
  no-multi-spaces: "error"
  space-in-parens: "error"
  no-multiple-empty-lines: "error"
  prefer-const: "error"
  no-use-before-define: "error"
