// Generated by CoffeeScript 2.5.1
// # Route Help

// Print the help to stderr.

// ## Source code
module.exports = function({argv, params, error, stderr, stderr_end}) {
  var command;
  command = this.helping(params);
  if (error) {
    stderr.write(`\n${error.message}\n`);
  }
  stderr.write(this.help(command));
  if (stderr_end) {
    stderr.end();
  }
  return null;
};
