// Generated by CoffeeScript 2.5.1
// # Parameters

// Usage: `parameters(config)`
var Parameters;

Parameters = require('./Parameters');

require('./plugins/router');

require('./plugins/config');

require('./plugins/args');

require('./plugins/help');

module.exports = function(config) {
  return new Parameters(config);
};
