// Generated by CoffeeScript 2.5.1
// # Shell.js

// Usage: `shell(config)`
var Shell;

Shell = require('./Shell');

require('./plugins/router');

require('./plugins/config');

require('./plugins/args');

require('./plugins/help');

module.exports = function(config) {
  return new Shell(config);
};
