// Generated by CoffeeScript 2.4.1
module.exports = function(config) {
  var client, endpoint, packageDefinition, proto_path, shell_proto;
  // Load the definition
  proto_path = path.resolve(__dirname, './shell.proto');
  packageDefinition = protoLoader.loadSync(proto_path, {
    keepCase: true,
    longs: String,
    enums: String,
    defaults: true,
    oneofs: true
  });
  shell_proto = grpc.loadPackageDefinition(packageDefinition).shell;
  // Instantiate the server
  endpoint = `${appconfig.grpc.address}:${appconfig.grpc.port}`;
  endpoint = `${config.address}:${config.port}`;
  client = new shell_proto.Shell('localhost:50051', grpc.credentials.createInsecure());
  return client;
};

// client.ping name: 'pong', (err, response) ->
//   console.log 'Greeting:', response.message
