// Generated by CoffeeScript 2.5.1
// Dependencies
var grpc, proto;

proto = require('@shell-js/grpc_proto');

try {
  grpc = require('grpc');
} catch (error) {
  grpc = require('@grpc/grpc-js');
}

module.exports = function(config = {}) {
  var client, endpoint, k, packageDefinition, ref, service, shell_proto;
  if (config.address == null) {
    config.address = '127.0.0.1';
  }
  if (config.port == null) {
    config.port = 50051;
  }
  // Load the definition
  packageDefinition = proto.loadSync();
  shell_proto = grpc.loadPackageDefinition(packageDefinition).shell;
  // Instantiate the client
  endpoint = `${config.address}:${config.port}`;
  client = new shell_proto.Shell(endpoint, grpc.credentials.createInsecure());
  ref = shell_proto.Shell.service;
  for (k in ref) {
    service = ref[k];
    // Response stream return a readable stream
    // Otherwise, convert the callback approach to a promise
    if (service.responseStream !== true) {
      client[k] = (function(handler) {
        return function() {
          var args, self;
          self = this;
          args = arguments;
          return new Promise(function(resolve, reject) {
            return handler.call(self, ...args, function(err, response) {
              if (err) {
                return reject(err);
              } else {
                return resolve(response);
              }
            });
          });
        };
      })(client[k]);
    }
  }
  return client;
};
