// Generated by CoffeeScript 2.0.2
module.exports = function() {
  var clone, copy, from, i, inverse, j, name, options, ref, ref1, src, target, to;
  target = arguments[0];
  from = 1;
  to = arguments.length;
  if (typeof target === 'boolean') {
    inverse = !!target;
    target = arguments[1];
    from = 2;
  }
  if (target == null) {
    target = {};
  }
  // Handle case when target is a string or something (possible in deep copy)
  if (typeof target !== "object" && typeof target !== 'function') {
    target = {};
  }
  for (i = j = ref = from, ref1 = to; ref <= ref1 ? j < ref1 : j > ref1; i = ref <= ref1 ? ++j : --j) {
    // Only deal with non-null/undefined values
    if ((options = arguments[i]) !== null) {
      // Extend the base object
      for (name in options) {
        src = target[name];
        copy = options[name];
        if (target === copy) {
          // Prevent never-ending loop
          continue;
        }
        // Recurse if we're merging plain objects
        if ((copy != null) && typeof copy === 'object' && !Array.isArray(copy) && !(copy instanceof RegExp) && !Buffer.isBuffer(copy)) {
          clone = src && (src && typeof src === 'object' ? src : {});
          // Never move original objects, clone them
          target[name] = module.exports(false, clone, copy);
        // Don't bring in undefined values
        } else if (copy !== void 0) {
          if (Array.isArray(copy)) {
            copy = copy.slice(0);
          }
          if (!(inverse && typeof target[name] !== 'undefined')) {
            target[name] = copy;
          }
        }
      }
    }
  }
  // Return the modified object
  return target;
};
