// Generated by CoffeeScript 2.4.1
// # Route Help

// Print the help to stderr.

// ## Source code
module.exports = function({argv, params, error, writer}) {
  var command;
  command = this.helping(params);
  if (error) {
    writer.write(`\n${error.message}\n`);
  }
  writer.write(this.help(command));
  writer.end();
  return null;
};
