// Generated by CoffeeScript 2.4.1
// # Route Help

// Print the help to stderr.

// ## Source code
module.exports = function({argv, params, config, error}) {
  var command, writer;
  command = this.helping(params);
  writer = config.help.writer;
  if (typeof writer === 'string') {
    switch (writer) {
      case 'stdout':
        writer = process.stdout;
        break;
      case 'stderr':
        writer = process.stderr;
    }
  }
  if (error) {
    writer.write(`\n${error.message}\n\n`);
  }
  writer.write(this.help(command));
  if (config.help.end) {
    return writer.end();
  }
};
