// Generated by CoffeeScript 2.5.1
var is_object_literal, mutate;

({mutate, is_object_literal} = require('mixme'));

/*
Format errors
*/
module.exports = function() {
  var arg, error, j, len, options;
  if (typeof arguments[0] === 'string') {
    arguments[0] = {
      message: arguments[0]
    };
  }
  if (Array.isArray(arguments[0])) {
    arguments[0] = {
      message: arguments[0]
    };
  }
  options = {};
  for (j = 0, len = arguments.length; j < len; j++) {
    arg = arguments[j];
    if (!is_object_literal(arg)) {
      throw Error(`Invalid Error Argument: expect an object literal, got ${JSON.stringify(arg)}.`);
    }
    mutate(options, arg);
  }
  if (Array.isArray(options.message)) {
    options.message = options.message.filter(function(i) {
      return i;
    }).join(' ');
  }
  error = new Error(options.message);
  if (options.command) {
    error.command = options.command;
  }
  return error;
};
