// Generated by CoffeeScript 2.0.2
var path;

path = require('path');

module.exports = function(module) {
  module = module.substr(0, 1) === '.' ? path.resolve(process.cwd(), module) : module;
  return require.main.require(module);
};
