// Generated by CoffeeScript 2.5.1
  // ## Plugin "args"

// Dependencies
var Shell, clone, is_object_literal, merge, set_default, utils,
  indexOf = [].indexOf;

utils = require('../utils');

({clone, is_object_literal, merge} = require('mixme'));

// Shell & plugins
Shell = require('../Shell');

// ## Method `parse([arguments])`

// Convert an arguments list to an object literal.

// * `arguments`: `[string] | process` The arguments to parse, accept the [Node.js process](https://nodejs.org/api/process.html) instance or an [argument list](https://nodejs.org/api/process.html#process_process_argv) provided as an array or a string, optional.
// * `options`: `object` Options used to alter the behavior of the `compile` method.
//   * `extended`: `boolean` The value `true` indicates that the extracted argument are returned in extended format, default to the configuration `extended` value which is `false` by default.
// * Returns: `object | [object]` The extracted arguments, a literal object in default flatten mode or an array in extended mode.
Shell.prototype.parse = function(argv = process, options = {}) {
  var appconfig, command_params, full_params, i, index, k, len, params, parse, v;
  appconfig = this.confx().get();
  if (options.extended == null) {
    options.extended = appconfig.extended;
  }
  index = 0;
  // Remove node and script argv elements
  if (argv === process) {
    index = 2;
    argv = argv.argv;
  } else if (!Array.isArray(argv)) {
    throw utils.error(['Invalid Arguments:', 'parse require arguments or process as first argument,', `got ${JSON.stringify(process)}`]);
  }
  // Extracted arguments
  full_params = [];
  parse = function(config, command) {
    var _, err, helping, i, key, leftover, len, main, option, params, ref, ref1, ref2, required, shortcut, type, value, values;
    full_params.push(params = {});
    if (command != null) {
      // Add command name provided by parent
      params[appconfig.command] = command;
    }
    // Read options
    while (true) {
      if (argv.length === index || argv[index][0] !== '-') {
        break;
      }
      key = argv[index++];
      shortcut = key[1] !== '-';
      key = key.substring((shortcut ? 1 : 2), key.length);
      if (shortcut) {
        shortcut = key;
      }
      if (shortcut) {
        key = config.shortcuts[shortcut];
      }
      option = (ref = config.options) != null ? ref[key] : void 0;
      if (!shortcut && config.strict && !option) {
        err = utils.error(['Invalid Argument:', `the argument ${shortcut ? "-" : "--"}${key} is not a valid option`]);
        err.command = full_params.slice(1).map(function(params) {
          return params[appconfig.command];
        });
        throw err;
      }
      if (shortcut && !option) {
        throw utils.error(['Invalid Shortcut Argument:', `the \"-${shortcut}\" argument is not a valid option`, Array.isArray(config.command) ? `in command \"${config.command.join(' ')}\"` : void 0]);
      }
      // Auto discovery
      if (!option) {
        type = argv[index] && argv[index][0] !== '-' ? 'string' : 'boolean';
        option = {
          name: key,
          type: type
        };
      }
      switch (option.type) {
        case 'boolean':
          params[key] = true;
          break;
        case 'string':
          value = argv[index++];
          if (!((value != null) && value[0] !== '-')) {
            throw utils.error(['Invalid Option:', `no value found for option ${JSON.stringify(key)}`]);
          }
          params[key] = value;
          break;
        case 'integer':
          value = argv[index++];
          if (!((value != null) && value[0] !== '-')) {
            throw utils.error(['Invalid Option:', `no value found for option ${JSON.stringify(key)}`]);
          }
          params[key] = parseInt(value, 10);
          if (isNaN(params[key])) {
            throw utils.error(['Invalid Option:', `value of ${JSON.stringify(key)} is not an integer,`, `got ${JSON.stringify(value)}`]);
          }
          break;
        case 'array':
          value = argv[index++];
          if (!((value != null) && value[0] !== '-')) {
            throw utils.error(['Invalid Option:', `no value found for option ${JSON.stringify(key)}`]);
          }
          if (params[key] == null) {
            params[key] = [];
          }
          params[key].push(...value.split(','));
      }
    }
    // Check if help is requested
    // TODO: this doesnt seem right, also, the test in help.parse seems wrong as well
    helping = false;
    ref1 = config.options;
    for (_ in ref1) {
      option = ref1[_];
      if (option.help !== true) {
        continue;
      }
      if (params[option.name]) {
        helping = true;
      }
    }
    if (helping) {
      return params;
    }
    ref2 = config.options;
    // Check against required options
    for (_ in ref2) {
      option = ref2[_];
      // Handler required
      required = typeof option.required === 'function' ? !!option.required.call(null, {
        config: config,
        command: command
      }) : !!option.required;
      if (required && (params[option.name] == null)) {
        throw utils.error(['Required Option:', `the \"${option.name}\" option must be provided`]);
      }
      // Handle enum
      if (option.enum) {
        values = params[option.name];
        if (!required && values !== void 0) {
          if (!Array.isArray(values)) {
            values = [values];
          }
          for (i = 0, len = values.length; i < len; i++) {
            value = values[i];
            if (indexOf.call(option.enum, value) < 0) {
              throw utils.error(['Invalid Argument Value:', `the value of option \"${option.name}\"`, `must be one of ${JSON.stringify(option.enum)},`, `got ${JSON.stringify(value)}`]);
            }
          }
        }
      }
    }
    // We still have some argument to parse
    if (argv.length !== index) {
      // Store the full command in the return array
      leftover = argv.slice(index);
      if (config.main) {
        params[config.main.name] = leftover;
      } else {
        command = argv[index++];
        if (!config.commands[command]) {
          // Validate the command
          throw utils.error(['Invalid Argument:', `fail to interpret all arguments \"${leftover.join(' ')}\"`]);
        }
        // Parse child configuration
        parse(config.commands[command], command);
      }
    } else if (config.main) {
      params[config.main.name] = [];
    }
    // NOTE: legacy versions used to inject an help command
    // when parsing arguments which doesnt hit a sub command
    // See the associated tests in "help/parse.coffee"
    // Happens with global options without a command
    // if Object.keys(config.commands).length and not command
    //   params[appconfig.command] = 'help'
    // Check against required main
    main = config.main;
    if (main) {
      required = typeof main.required === 'function' ? !!main.required.call(null, {
        config: config,
        command: command
      }) : !!main.required;
      if (required && params[main.name].length === 0) {
        throw utils.error(['Required Main Argument:', `no suitable arguments for ${JSON.stringify(main.name)}`]);
      }
    }
    return params;
  };
  // Start the parser
  parse(appconfig, null);
  if (!options.extended) {
    params = {};
    if (Object.keys(appconfig.commands).length) {
      params[appconfig.command] = [];
    }
    for (i = 0, len = full_params.length; i < len; i++) {
      command_params = full_params[i];
      for (k in command_params) {
        v = command_params[k];
        if (k === appconfig.command) {
          params[k].push(v);
        } else {
          params[k] = v;
        }
      }
    }
  } else {
    params = full_params;
  }
  // Enrich params with default values
  set_default(appconfig, params);
  return params;
};

// ## Method `compile(command, [options])`

// Convert an object to an arguments array.

// * `data`: `object` The parameter object to be converted into an array of arguments, optional.
// * `options`: `object` Options used to alter the behavior of the `compile` method.
//   * `extended`: `boolean` The value `true` indicates that the object literal are provided in extended format, default to the configuration `extended` value which is `false` by default.
//   * `script`: `string` The JavaScript file being executed by the engine, when present, the engine and the script names will prepend the returned arguments, optional, default is false.
// * Returns: `array` The command line arguments.
Shell.prototype.compile = function(data, options = {}) {
  var appconfig, argv, compile, keys;
  argv = options.script ? [process.execPath, options.script] : [];
  appconfig = this.confx().get();
  if (options.extended == null) {
    options.extended = appconfig.extended;
  }
  if (!is_object_literal(options)) {
    throw utils.error(['Invalid Compile Arguments:', '2nd argument option must be an object,', `got ${JSON.stringify(options)}`]);
  }
  keys = {};
  // In extended mode, the data array will be truncated
  // data = merge data unless extended
  set_default(appconfig, data);
  if (typeof data[appconfig.command] === 'string') {
    // Convert command parameter to a 1 element array if provided as a string
    data[appconfig.command] = [data[appconfig.command]];
  }
  // Compile
  compile = function(config, ldata) {
    var _, command, has_child_commands, i, key, len, option, ref, required, results, val, value;
    ref = config.options;
    for (_ in ref) {
      option = ref[_];
      key = option.name;
      keys[key] = true;
      value = ldata[key];
      // Handle required
      required = typeof option.required === 'function' ? !!option.required.call(null, {
        config: config,
        command: command
      }) : !!option.required;
      if (required && (value == null)) {
        throw utils.error(['Required Option:', `the \"${key}\" option must be provided`]);
      }
      // Validate value against option "enum"
      if ((value != null) && option.enum) {
        if (!Array.isArray(value)) {
          value = [value];
        }
        for (i = 0, len = value.length; i < len; i++) {
          val = value[i];
          if (indexOf.call(option.enum, val) < 0) {
            throw utils.error(['Invalid Parameter Value:', `the value of option \"${option.name}\"`, `must be one of ${JSON.stringify(option.enum)},`, `got ${JSON.stringify(val)}`]);
          }
        }
      }
      // Serialize
      if (value) {
        switch (option.type) {
          case 'boolean':
            argv.push(`--${key}`);
            break;
          case 'string':
          case 'integer':
            argv.push(`--${key}`);
            argv.push(`${value}`);
            break;
          case 'array':
            argv.push(`--${key}`);
            argv.push(`${value.join(',')}`);
        }
      }
    }
    if (config.main) {
      value = ldata[config.main.name];
      // Handle required
      required = typeof config.main.required === 'function' ? !!config.main.required.call(null, {
        config: config,
        command: command
      }) : !!config.main.required;
      if (required && (value == null)) {
        throw utils.error(['Required Main Parameter:', `no suitable arguments for ${JSON.stringify(config.main.name)}`]);
      }
      if (value != null) {
        if (!Array.isArray(value)) {
          throw utils.error(['Invalid Parameter Type:', `expect main to be an array, got ${JSON.stringify(value)}`]);
        }
        keys[config.main.name] = value;
        argv = argv.concat(value);
      }
    }
    // Recursive
    has_child_commands = options.extended ? data.length : Object.keys(config.commands).length;
    if (has_child_commands) {
      command = options.extended ? data[0][appconfig.command] : data[appconfig.command].shift();
      if (!config.commands[command]) {
        throw utils.error(['Invalid Command Parameter:', `command ${JSON.stringify(command)} is not registed,`, `expect one of ${JSON.stringify(Object.keys(config.commands).sort())}`, Array.isArray(config.command) ? `in command ${JSON.stringify(config.command.join(' '))}` : void 0]);
      }
      argv.push(command);
      keys[appconfig.command] = command;
      // Compile child configuration
      compile(config.commands[command], options.extended ? data.shift() : ldata);
    }
    if (options.extended || !has_child_commands) {
// Handle data not defined in the configuration
// Note, they are always pushed to the end and associated with the deepest child
      results = [];
      for (key in ldata) {
        value = ldata[key];
        if (keys[key]) {
          continue;
        }
        if (appconfig.strict) {
          throw utils.error(['Invalid Parameter:', `the property --${key} is not a registered argument`].join(' '));
        }
        if (typeof value === 'boolean') {
          if (value) {
            results.push(argv.push(`--${key}`));
          } else {
            results.push(void 0);
          }
        } else if (typeof value === 'undefined' || value === null) {

        } else {
          // nothing
          argv.push(`--${key}`);
          results.push(argv.push(`${value}`));
        }
      }
      return results;
    }
  };
  compile(appconfig, options.extended ? data.shift() : data);
  return argv;
};

// ## Utils

// Given a configuration, apply default values to an object.
set_default = function(config, data, tempdata = null) {
  var _, command, name, option, ref;
  if (tempdata == null) {
    tempdata = merge(data);
  }
  if (Object.keys(config.commands).length) {
    command = tempdata[config.command];
    if (Array.isArray(command)) {
      command = tempdata[config.command].shift();
    }
    // We are not validating if the command is valid, it may not be set if help option is present
    // throw Error "Invalid Command: \"#{command}\"" unless config.commands[command]
    if (config.commands[command]) {
      data = set_default(config.commands[command], data, tempdata);
    }
  }
  ref = config.options;
  for (_ in ref) {
    option = ref[_];
    if (option.default != null) {
      if (data[name = option.name] == null) {
        data[name] = option.default;
      }
    }
  }
  return data;
};
